## Parsing HTML Files for Data

In [1]:
import pandas as pd
from io import StringIO
from bs4 import BeautifulSoup, Comment
import re
import os
from pathlib import Path

In [ ]:
print(f'Current: {os.getcwd()}')
os.chdir('/Users/camsmithers/Desktop/Camalytics/NBA')
print(f'Current: {os.getcwd()}')

In [ ]:
games_path = Path("Data-NBA/Games/Games_2025-26")
game_data = []

In [ ]:
basic_dfs = []

for game in os.listdir(games_path):
    with open(f"Data-NBA/Games/Games_2025-26/{game}", encoding="utf-8", errors='replace') as f:
        page = f.read()
    soup = BeautifulSoup(page, "html.parser")

    basic_tables = soup.find_all(id=re.compile(r"^box-.*-game-basic$"))

    table_dfs = []
    for table in basic_tables:
        table_id = table.get("id")
        table_html = str(table)
        df = pd.read_html(StringIO(table_html), header=1)[0]
        df["team_table_id"] = table_id
        df["game_id"] = game
        table_dfs.append(df)

    # Add the opposing team table id
    if len(table_dfs) == 2:
        table_dfs[0]["opp_team_table_id"] = table_dfs[1]["team_table_id"]
        table_dfs[1]["opp_team_table_id"] = table_dfs[0]["team_table_id"]

    basic_dfs.extend(table_dfs)

basic_tables_combined = pd.concat(basic_dfs, ignore_index=True)

In [10]:
basic_tables_combined

,Starters,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,...,STL,BLK,TOV,PF,PTS,GmSc,+/-,team_table_id,game_id,opp_team_table_id
0,Stephon Castle,33:26,8,15,.533,3,5,.600,1,1,...,0,0,5,4,20,10.8,+5,box-SAS-game-basic,202604020LAC.html,box-LAC-game-basic
1,De'Aaron Fox,29:10,9,13,.692,1,4,.250,3,4,...,3,0,3,4,22,20.4,+24,box-SAS-game-basic,202604020LAC.html,box-LAC-game-basic
2,Devin Vassell,28:52,5,12,.417,3,8,.375,1,1,...,0,0,0,1,14,12.4,+4,box-SAS-game-basic,202604020LAC.html,box-LAC-game-basic
3,Julian Champagnie,27:33,5,13,.385,1,6,.167,2,3,...,2,0,1,1,13,12.1,+17,box-SAS-game-basic,202604020LAC.html,box-LAC-game-basic
4,Luke Kornet,25:04,2,3,.667,0,0,NaN,4,4,...,0,0,0,1,8,12.4,+14,box-SAS-game-basic,202604020LAC.html,box-LAC-game-basic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40044,Will Riley,5:59,1,3,.333,0,1,.000,0,0,...,0,0,0,1,2,1.2,-9,box-WAS-game-basic,202511010WAS.html,box-ORL-game-basic
40045,Justin Champagnie,5:10,1,3,.333,0,0,NaN,0,0,...,0,0,0,0,2,1.6,-7,box-WAS-game-basic,202511010WAS.html,box-ORL-game-basic
40046,Tristan Vukcevic,5:10,0,2,.000,0,1,.000,0,0,...,0,0,1,1,0,-2.8,-7,box-WAS-game-basic,202511010WAS.html,box-ORL-game-basic
40047,Anthony Gill,4:05,0,1,.000,0,0,NaN,0,0,...,0,0,0,0,0,0.0,-7,box-WAS-game-basic,202511010WAS.html,NaN
40048,Team Totals,240,39,98,.398,9,27,.333,7,15,...,7,9,17,23,94,NaN,NaN,box-WAS-game-basic,202511010WAS.html,NaN

In [ ]:
advanced_dfs = []

for game in os.listdir(games_path):
    with open(f"Data-NBA/Games/Games_2025-26/{game}", encoding="utf-8", errors='replace') as f:
        page = f.read()
    soup = BeautifulSoup(page, "html.parser")

    advanced_tables = soup.find_all(id=re.compile(r"^box-.*-game-advanced$"))

    table_dfs = []
    for table in advanced_tables:
        table_id = table.get("id")
        table_html = str(table)
        df = pd.read_html(StringIO(table_html), header=1)[0]
        df["team_table_id"] = table_id
        df["game_id"] = game
        table_dfs.append(df)

    # Add the opposing team table id
    if len(table_dfs) == 2:
        table_dfs[0]["opp_team_table_id"] = table_dfs[1]["team_table_id"]
        table_dfs[1]["opp_team_table_id"] = table_dfs[0]["team_table_id"]

    advanced_dfs.extend(table_dfs)

advanced_tables_combined = pd.concat(advanced_dfs, ignore_index=True)

In [12]:
advanced_tables_combined

,Starters,MP,TS%,eFG%,3PAr,FTr,ORB%,DRB%,TRB%,AST%,...,BLK%,TOV%,USG%,ORtg,DRtg,BPM,team_table_id,game_id,opp_team_table_id,Unnamed: 16
0,Stephon Castle,33:26,.648,.633,.333,.067,0.0,12.0,6.7,20.2,...,0.0,24.5,26.6,103,106,-3.3,box-SAS-game-advanced,202604020LAC.html,box-LAC-game-advanced,NaN
1,De'Aaron Fox,29:10,.745,.731,.308,.308,0.0,27.4,15.3,25.6,...,0.0,16.9,26.5,129,91,10.2,box-SAS-game-advanced,202604020LAC.html,box-LAC-game-advanced,NaN
2,Devin Vassell,28:52,.563,.542,.667,.083,8.8,27.7,19.3,8.6,...,0.0,0.0,18.8,130,102,3.0,box-SAS-game-advanced,202604020LAC.html,box-LAC-game-advanced,NaN
3,Julian Champagnie,27:33,.454,.423,.462,.231,9.2,21.8,16.2,18.2,...,0.0,6.5,24.2,109,96,2.7,box-SAS-game-advanced,202604020LAC.html,box-LAC-game-advanced,NaN
4,Luke Kornet,25:04,.840,.667,.000,1.333,10.1,16.0,13.4,22.2,...,0.0,0.0,8.3,198,105,10.9,box-SAS-game-advanced,202604020LAC.html,box-LAC-game-advanced,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40044,Will Riley,5:59,.333,.333,.333,.000,0.0,43.4,17.3,25.9,...,0.0,0.0,19.8,83,117,-7.0,box-WAS-game-advanced,202511010WAS.html,box-ORL-game-advanced,NaN
40045,Justin Champagnie,5:10,.333,.333,.000,.000,16.6,50.2,30.0,0.0,...,0.0,0.0,22.9,83,116,-6.5,box-WAS-game-advanced,202511010WAS.html,box-ORL-game-advanced,NaN
40046,Tristan Vukcevic,5:10,.000,.000,.500,.000,0.0,0.0,0.0,0.0,...,0.0,33.3,22.9,0,124,-33.2,box-WAS-game-advanced,202511010WAS.html,box-ORL-game-advanced,NaN
40047,Anthony Gill,4:05,.000,.000,.000,.000,21.0,0.0,12.6,0.0,...,0.0,0.0,9.7,52,124,-13.4,box-WAS-game-advanced,202511010WAS.html,NaN,NaN
40048,Team Totals,240,.449,.444,.276,.153,19.6,78.4,43.0,48.7,...,16.1,14.0,100.0,87.0,115.7,NaN,box-WAS-game-advanced,202511010WAS.html,NaN,NaN

In [ ]:
basic_tables_combined.to_csv("Data-NBA/Adding-2526/BasicBox2526.csv")
advanced_tables_combined.to_csv("Data-NBA/Adding-2526/AdvancedBox2526.csv")

In [ ]:
all_teams = Path("Data-NBA/Archive/Teams/Teams_2526/All_Teams")
playoff_teams = Path("Data-NBA/Archive/Teams/Teams_2526/Playoff_Teams")

In [ ]:
all_general_dfs = []

for team in os.listdir(all_teams):
    if team.endswith(".html"):
        with open(f"Data-NBA/Archive/Teams/Teams_2526/All_Teams/{team}", encoding='utf-8', errors='replace') as f:
            page = f.read()
        
        soup = BeautifulSoup(page, "html.parser")

        comment = next(c for c in soup.find_all(string=lambda text: isinstance(text, Comment)) if "team_and_opponent" in c)
        table = BeautifulSoup(comment, "html.parser").find(id="team_and_opponent")
        df = pd.read_html(StringIO(str(table)))[0]
        df["team_id"] = team
        all_general_dfs.append(df)

all_general_dfs = pd.concat(all_general_dfs, ignore_index=True)

In [ ]:
all_misc_dfs = []

for team in os.listdir(all_teams):
    if team.endswith(".html"):
        with open(f"Data-NBA/Archive/Teams/Teams_2526/All_Teams/{team}", encoding='utf-8', errors='replace') as f:
            page = f.read()
        
        soup = BeautifulSoup(page, "html.parser")

        comment = next(c for c in soup.find_all(string=lambda text: isinstance(text, Comment)) if "team_misc" in c)
        table = BeautifulSoup(comment, "html.parser").find(id="team_misc")
        df = pd.read_html(StringIO(str(table)), header=1)[0]
        df["team_id"] = team
        all_misc_dfs.append(df)

all_misc_combined = pd.concat(all_misc_dfs, ignore_index=True)

In [ ]:
all_pgs_dfs = []

for team in os.listdir(all_teams):
    with open(f"Data-NBA/Archive/Teams/Teams_2526/All_Teams/{team}", encoding='utf-8', errors='replace') as f:
        page = f.read()
    
    soup = BeautifulSoup(page, "html.parser")

    tables = soup.find_all(id="per_game_stats")

    for table in tables:
        table_html = str(table)
        df = pd.read_html(StringIO(table_html))[0]
        df["team_id"] = team
        all_pgs_dfs.append(df)
all_pgs_combined = pd.concat(all_pgs_dfs, ignore_index=True)

all_pgs_combined

,Rk,Player,Age,Pos,G,GS,MP,FG,FGA,FG%,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,team_id
0,1.0,Tyrese Maxey,25.0,PG,70,70,38.0,9.9,21.4,0.462,...,3.8,4.1,6.6,1.9,0.8,2.4,2.2,28.3,"CPOY-7,AS,NBA3",PHI-2025.html
1,2.0,VJ Edgecombe,20.0,SG,75,75,35.0,6.0,13.7,0.438,...,4.0,5.6,4.2,1.4,0.5,1.8,2.9,16.0,ROY-3,PHI-2025.html
2,3.0,Joel Embiid,31.0,C,38,38,31.6,9.0,18.3,0.489,...,5.7,7.7,3.9,0.6,1.2,2.9,2.2,26.9,NaN,PHI-2025.html
3,4.0,Kelly Oubre Jr.,30.0,SF,50,41,31.5,5.1,10.9,0.467,...,4.0,5.0,1.6,1.4,0.5,1.4,2.5,14.1,NaN,PHI-2025.html
4,5.0,Paul George,35.0,PF,37,37,30.7,6.1,13.9,0.439,...,4.8,5.3,3.6,1.7,0.4,1.7,2.3,17.3,NaN,PHI-2025.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
686,21.0,Luke Travers,24.0,SG,12,0,8.6,0.8,3.0,0.250,...,1.3,2.0,0.8,0.6,0.3,0.3,0.5,2.3,NaN,CLE-2025.html
687,22.0,Riley Minix,25.0,SF,6,0,8.3,1.7,2.8,0.588,...,0.5,0.7,0.7,0.2,0.2,0.5,0.7,4.3,NaN,CLE-2025.html
688,23.0,Chris Livingston,22.0,SF,3,0,5.7,1.3,2.3,0.571,...,1.0,1.0,0.3,0.3,0.0,0.0,1.3,3.0,NaN,CLE-2025.html
689,24.0,Darius Brown II,26.0,SG,1,0,3.0,0.0,1.0,0.000,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,CLE-2025.html
690,NaN,Team Totals,NaN,NaN,82,82,240.9,43.3,90.0,0.482,...,32.7,44.4,28.3,8.5,5.0,14.0,19.6,119.5,NaN,CLE-2025.html

In [ ]:
playoff_pgs_dfs = []

for team in os.listdir(playoff_teams):
    with open(f"Data-NBA/Archive/Teams/Teams_2526/Playoff_Teams/{team}", encoding='utf-8', errors='replace') as f:
        page = f.read()
    
    soup = BeautifulSoup(page, "html.parser")

    tables = soup.find_all(id="per_game_stats_post")

    for table in tables:
        table_html = str(table)
        df = pd.read_html(StringIO(table_html))[0]
        df["team_id"] = team
        playoff_pgs_dfs.append(df)
playoff_pgs_combined = pd.concat(playoff_pgs_dfs, ignore_index=True)

playoff_pgs_combined

,Rk,Player,Age,Pos,G,GS,MP,FG,FGA,FG%,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,team_id
0,1.0,Tyrese Maxey,25.0,PG,11,11,39.7,8.7,19.2,0.455,...,3.6,4.0,5.9,0.8,0.4,2.1,2.0,23.7,NaN,PHI-2025.html
1,2.0,VJ Edgecombe,20.0,SG,11,11,37.0,5.5,13.2,0.414,...,4.0,6.1,3.4,1.0,0.4,1.6,2.6,14.0,NaN,PHI-2025.html
2,3.0,Paul George,35.0,PF,11,11,35.8,5.9,12.9,0.458,...,3.4,3.9,3.0,1.3,0.5,2.0,2.5,16.4,NaN,PHI-2025.html
3,4.0,Joel Embiid,31.0,C,7,7,33.3,8.1,17.7,0.460,...,6.1,7.3,5.4,0.3,0.9,2.1,2.4,24.0,NaN,PHI-2025.html
4,5.0,Kelly Oubre Jr.,30.0,SF,11,11,33.1,4.4,9.6,0.453,...,4.7,5.8,1.1,0.5,0.5,0.7,2.5,11.6,NaN,PHI-2025.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,12.0,Tyrese Proctor,21.0,PG,4,0,3.3,0.0,0.5,0.000,...,0.3,0.3,0.5,0.0,0.0,0.5,0.3,0.5,NaN,CLE-2025.html
242,13.0,Craig Porter Jr.,25.0,PG,7,0,3.0,0.1,0.4,0.333,...,0.4,0.4,0.6,0.0,0.0,0.6,0.1,0.3,NaN,CLE-2025.html
243,14.0,Nae'Qwan Tomlin,25.0,PF,7,0,2.7,0.6,0.9,0.667,...,0.1,0.7,0.3,0.1,0.0,0.1,0.4,1.3,NaN,CLE-2025.html
244,15.0,Larry Nance Jr.,33.0,PF,2,0,2.5,0.0,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,NaN,CLE-2025.html
245,NaN,Team Totals,NaN,NaN,18,18,244.2,37.4,82.1,0.456,...,29.3,40.9,21.7,7.9,5.1,16.7,20.4,107.9,NaN,CLE-2025.html

In [ ]:
all_totals_dfs = []

for team in os.listdir(all_teams):
    if team.endswith(".html"):
        with open(f"Data-NBA/Archive/Teams/Teams_2526/All_Teams/{team}", encoding='utf-8', errors='replace') as f:
            page = f.read()
        
        soup = BeautifulSoup(page, "html.parser")

        comment = next(c for c in soup.find_all(string=lambda text: isinstance(text, Comment)) if "totals_stats" in c)
        table = BeautifulSoup(comment, "html.parser").find(id="totals_stats")
        df = pd.read_html(StringIO(str(table)))[0]
        df["team_id"] = team
        all_totals_dfs.append(df)

all_totals_combined = pd.concat(all_totals_dfs, ignore_index=True)

In [ ]:
playoff_totals_dfs = []

for team in os.listdir(playoff_teams):
    if team.endswith(".html"):
        with open(f"Data-NBA/Archive/Teams/Teams_2526/Playoff_Teams/{team}", encoding='utf-8', errors='replace') as f:
            page = f.read()
        
        soup = BeautifulSoup(page, "html.parser")

        comment = next(c for c in soup.find_all(string=lambda text: isinstance(text, Comment)) if "totals_stats_post" in c)
        table = BeautifulSoup(comment, "html.parser").find(id="totals_stats_post")
        df = pd.read_html(StringIO(str(table)))[0]
        df["team_id"] = team
        playoff_totals_dfs.append(df)

playoff_totals_combined = pd.concat(playoff_totals_dfs, ignore_index=True)

In [ ]:
all_per36_dfs = []

for team in os.listdir(all_teams):
    if team.endswith(".html"):
        with open(f"Data-NBA/Archive/Teams/Teams_2526/All_Teams/{team}", encoding='utf-8', errors='replace') as f:
            page = f.read()
        
        soup = BeautifulSoup(page, "html.parser")

        tables = soup.find_all(id="per_minute_stats")

        for table in tables:
            table_html = str(table)
            df = pd.read_html(StringIO(table_html))[0]
            df["team_id"] = team
            all_per36_dfs.append(df)

all_per36_combined = pd.concat(all_per36_dfs, ignore_index=True)

all_per36_combined

,Rk,Player,Age,Pos,G,GS,MP,FG,FGA,FG%,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,team_id
0,1,Tyrese Maxey,25,PG,70,70,2661,9.4,20.3,0.462,...,3.6,3.9,6.2,1.8,0.7,2.3,2.0,26.8,"CPOY-7,AS,NBA3",PHI-2025.html
1,2,VJ Edgecombe,20,SG,75,75,2623,6.2,14.1,0.438,...,4.1,5.8,4.3,1.5,0.5,1.9,2.9,16.5,ROY-3,PHI-2025.html
2,3,Quentin Grimes,25,SG,75,19,2206,5.5,12.3,0.450,...,3.7,4.5,4.0,1.0,0.5,2.2,2.5,16.4,NaN,PHI-2025.html
3,4,Dominick Barlow,22,PF,71,59,1689,4.6,8.5,0.539,...,4.4,7.2,1.9,1.3,1.1,1.2,3.2,11.6,NaN,PHI-2025.html
4,5,Kelly Oubre Jr.,30,SF,50,41,1574,5.8,12.4,0.467,...,4.6,5.8,1.8,1.6,0.5,1.6,2.9,16.1,NaN,PHI-2025.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
656,20,Tristan Enaruna,24,SF,9,0,85,5.9,11.9,0.500,...,3.0,5.9,3.0,2.1,0.0,1.3,1.3,15.7,NaN,CLE-2025.html
657,21,Riley Minix,25,SF,6,0,50,7.2,12.2,0.588,...,2.2,2.9,2.9,0.7,0.7,2.2,2.9,18.7,NaN,CLE-2025.html
658,22,Olivier Sarr,26,C,4,0,39,4.6,6.5,0.714,...,8.3,10.2,4.6,1.8,2.8,1.8,8.3,12.9,NaN,CLE-2025.html
659,23,Chris Livingston,22,SF,3,0,17,8.5,14.8,0.571,...,6.4,6.4,2.1,2.1,0.0,0.0,8.5,19.1,NaN,CLE-2025.html
660,24,Darius Brown II,26,SG,1,0,3,0.0,12.0,0.000,...,12.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,CLE-2025.html

In [ ]:
playoff_per36_dfs = []

for team in os.listdir(playoff_teams):
    if team.endswith(".html"):
        with open(f"Data-NBA/Archive/Teams/Teams_2526/Playoff_Teams/{team}", encoding='utf-8', errors='replace') as f:
            page = f.read()
        
        soup = BeautifulSoup(page, "html.parser")

        tables = soup.find_all(id="per_minute_stats_post")

        for table in tables:
            table_html = str(table)
            df = pd.read_html(StringIO(table_html))[0]
            df["team_id"] = team
            playoff_per36_dfs.append(df)

playoff_per36_combined = pd.concat(playoff_per36_dfs, ignore_index=True)

playoff_per36_combined

,Rk,Player,Age,Pos,G,GS,MP,FG,FGA,FG%,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,team_id
0,1,Tyrese Maxey,25,PG,11,11,437,7.9,17.4,0.455,...,3.3,3.6,5.4,0.7,0.3,1.9,1.8,21.5,NaN,PHI-2025.html
1,2,VJ Edgecombe,20,SG,11,11,407,5.3,12.8,0.414,...,3.9,5.9,3.3,1.0,0.4,1.6,2.6,13.6,NaN,PHI-2025.html
2,3,Paul George,35,PF,11,11,394,5.9,13.0,0.458,...,3.4,3.9,3.0,1.3,0.5,2.0,2.5,16.4,NaN,PHI-2025.html
3,4,Kelly Oubre Jr.,30,SF,11,11,364,4.7,10.5,0.453,...,5.1,6.3,1.2,0.5,0.5,0.8,2.8,12.7,NaN,PHI-2025.html
4,5,Quentin Grimes,25,SG,11,0,243,3.4,8.6,0.397,...,4.1,4.4,3.7,0.4,0.7,0.9,3.1,11.0,NaN,PHI-2025.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,11,Thomas Bryant,28,C,9,0,41,5.3,18.4,0.286,...,7.0,9.7,1.8,1.8,0.9,1.8,3.5,14.9,NaN,CLE-2025.html
226,12,Craig Porter Jr.,25,PG,7,0,21,1.7,5.1,0.333,...,5.1,5.1,6.9,0.0,0.0,6.9,1.7,3.4,NaN,CLE-2025.html
227,13,Nae'Qwan Tomlin,25,PF,7,0,19,7.6,11.4,0.667,...,1.9,9.5,3.8,1.9,0.0,1.9,5.7,17.1,NaN,CLE-2025.html
228,14,Tyrese Proctor,21,PG,4,0,13,0.0,5.5,0.000,...,2.8,2.8,5.5,0.0,0.0,5.5,2.8,5.5,NaN,CLE-2025.html
229,15,Larry Nance Jr.,33,PF,2,0,5,0.0,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,7.2,0.0,0.0,NaN,CLE-2025.html

In [ ]:
all_per100_dfs = []

for team in os.listdir(all_teams):
    if team.endswith(".html"):
        with open(f"Data-NBA/Archive/Teams/Teams_2526/All_Teams/{team}", encoding='utf-8', errors='replace') as f:
            page = f.read()
        
        soup = BeautifulSoup(page, "html.parser")

        comment = next(c for c in soup.find_all(string=lambda text: isinstance(text, Comment)) if "per_poss" in c)
        table = BeautifulSoup(comment, "html.parser").find(id="per_poss")
        df = pd.read_html(StringIO(str(table)))[0]
        df["team_id"] = team
        all_per100_dfs.append(df)

all_per100_combined = pd.concat(all_per100_dfs, ignore_index=True)

all_per100_combined

,Rk,Player,Age,G,GS,MP,FG,FGA,FG%,3P,...,AST,STL,BLK,TOV,PF,PTS,ORtg,DRtg,Awards,team_id
0,1,Tyrese Maxey,25,70,70,2661,12.6,27.2,0.462,4.0,...,8.4,2.4,1.0,3.1,2.7,35.9,120.0,116,"CPOY-7,AS,NBA3",PHI-2025.html
1,2,VJ Edgecombe,20,75,75,2623,8.3,19.0,0.438,2.7,...,5.8,2.0,0.7,2.5,3.9,22.1,113.0,116,ROY-3,PHI-2025.html
2,3,Quentin Grimes,25,75,19,2206,7.4,16.5,0.450,2.8,...,5.3,1.4,0.6,2.9,3.4,22.0,115.0,118,NaN,PHI-2025.html
3,4,Dominick Barlow,22,71,59,1689,6.1,11.4,0.539,0.6,...,2.5,1.8,1.5,1.6,4.3,15.6,124.0,116,NaN,PHI-2025.html
4,5,Kelly Oubre Jr.,30,50,41,1574,7.8,16.7,0.467,2.6,...,2.5,2.1,0.7,2.1,3.9,21.6,114.0,116,NaN,PHI-2025.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
656,20,Tristan Enaruna,24,9,0,85,7.9,15.8,0.500,1.7,...,4.0,2.8,0.0,1.7,1.7,20.9,125.0,116,NaN,CLE-2025.html
657,21,Riley Minix,25,6,0,50,9.6,16.3,0.588,2.9,...,3.8,1.0,1.0,2.9,3.8,25.0,126.0,119,NaN,CLE-2025.html
658,22,Olivier Sarr,26,4,0,39,6.2,8.6,0.714,2.5,...,6.2,2.5,3.7,2.5,11.1,17.3,136.0,107,NaN,CLE-2025.html
659,23,Chris Livingston,22,3,0,17,11.3,19.8,0.571,0.0,...,2.8,2.8,0.0,0.0,11.3,25.4,129.0,112,NaN,CLE-2025.html
660,24,Darius Brown II,26,1,0,3,0.0,16.0,0.000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,114,NaN,CLE-2025.html

In [ ]:
playoff_per100_dfs = []

for team in os.listdir(playoff_teams):
    if team.endswith(".html"):
        with open(f"Data-NBA/Archive/Teams/Teams_2526/Playoff_Teams/{team}", encoding='utf-8', errors='replace') as f:
            page = f.read()
        
        soup = BeautifulSoup(page, "html.parser")

        comment = next(c for c in soup.find_all(string=lambda text: isinstance(text, Comment)) if "per_poss_post" in c)
        table = BeautifulSoup(comment, "html.parser").find(id="per_poss_post")
        df = pd.read_html(StringIO(str(table)))[0]
        df["team_id"] = team
        playoff_per100_dfs.append(df)

playoff_per100_combined = pd.concat(playoff_per100_dfs, ignore_index=True)

playoff_per100_combined

,Rk,Player,Age,G,GS,MP,FG,FGA,FG%,3P,...,AST,STL,BLK,TOV,PF,PTS,ORtg,DRtg,Awards,team_id
0,1,Tyrese Maxey,25,11,11,437,11.2,24.7,0.455,3.0,...,7.6,1.1,0.5,2.7,2.6,30.6,114.0,123,NaN,PHI-2025.html
1,2,VJ Edgecombe,20,11,11,407,7.5,18.2,0.414,2.6,...,4.7,1.4,0.5,2.3,3.6,19.4,105.0,121,NaN,PHI-2025.html
2,3,Paul George,35,11,11,394,8.4,18.4,0.458,4.5,...,4.3,1.8,0.6,2.9,3.5,23.4,110.0,121,NaN,PHI-2025.html
3,4,Kelly Oubre Jr.,30,11,11,364,6.7,14.9,0.453,1.4,...,1.7,0.7,0.7,1.1,3.9,18.0,111.0,121,NaN,PHI-2025.html
4,5,Quentin Grimes,25,11,0,243,4.8,12.2,0.397,2.9,...,5.3,0.6,1.1,1.3,4.4,15.6,119.0,122,NaN,PHI-2025.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,11,Thomas Bryant,28,9,0,41,7.4,25.8,0.286,2.5,...,2.5,2.5,1.2,2.5,4.9,20.9,88.0,110,NaN,CLE-2025.html
226,12,Craig Porter Jr.,25,7,0,21,2.4,7.2,0.333,0.0,...,9.6,0.0,0.0,9.6,2.4,4.8,56.0,119,NaN,CLE-2025.html
227,13,Nae'Qwan Tomlin,25,7,0,19,10.6,15.9,0.667,0.0,...,5.3,2.7,0.0,2.7,8.0,23.9,137.0,116,NaN,CLE-2025.html
228,14,Tyrese Proctor,21,4,0,13,0.0,7.8,0.000,0.0,...,7.8,0.0,0.0,7.8,3.9,7.8,65.0,121,NaN,CLE-2025.html
229,15,Larry Nance Jr.,33,2,0,5,0.0,0.0,NaN,0.0,...,0.0,0.0,0.0,10.1,0.0,0.0,0.0,124,NaN,CLE-2025.html

In [ ]:
all_advanced_dfs = []

for team in os.listdir(all_teams):
    if team.endswith(".html"):
        with open(f"Data-NBA/Archive/Teams/Teams_2526/All_Teams/{team}", encoding='utf-8', errors='replace') as f:
            page = f.read()
        
        soup = BeautifulSoup(page, "html.parser")

        comment = next(c for c in soup.find_all(string=lambda text: isinstance(text, Comment)) if 'id="advanced"' in c)
        table = BeautifulSoup(comment, "html.parser").find(id="advanced")
        df = pd.read_html(StringIO(str(table)))[0]
        df["team_id"] = team
        all_advanced_dfs.append(df)

all_advanced_combined = pd.concat(all_advanced_dfs, ignore_index=True)

all_advanced_combined

,Rk,Player,Age,Pos,G,GS,MP,PER,TS%,3PAr,...,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP,Awards,team_id
0,1.0,Tyrese Maxey,25.0,PG,70,70,2661,21.9,0.588,0.399,...,5.9,2.8,8.7,0.156,5.0,0.5,5.4,4.9,"CPOY-7,AS,NBA3",PHI-2025.html
1,2.0,VJ Edgecombe,20.0,SG,75,75,2623,14.0,0.540,0.409,...,1.9,2.5,4.4,0.081,-0.4,-0.1,-0.5,1.0,ROY-3,PHI-2025.html
2,3.0,Quentin Grimes,25.0,SG,75,19,2206,12.9,0.585,0.503,...,1.9,1.7,3.6,0.078,-0.9,-0.6,-1.6,0.2,NaN,PHI-2025.html
3,4.0,Dominick Barlow,22.0,PF,71,59,1689,13.2,0.597,0.206,...,2.2,1.8,3.9,0.112,-1.5,0.4,-1.1,0.4,NaN,PHI-2025.html
4,5.0,Kelly Oubre Jr.,30.0,SF,50,41,1574,13.0,0.580,0.439,...,1.1,1.6,2.7,0.083,-1.3,-0.1,-1.4,0.2,NaN,PHI-2025.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
686,21.0,Riley Minix,25.0,SF,6,0,50,15.0,0.710,0.529,...,0.1,0.0,0.1,0.119,-0.7,-1.3,-2.0,0.0,NaN,CLE-2025.html
687,22.0,Olivier Sarr,26.0,C,4,0,39,17.5,0.761,0.429,...,0.1,0.1,0.2,0.203,-1.7,4.3,2.6,0.0,NaN,CLE-2025.html
688,23.0,Chris Livingston,22.0,SF,3,0,17,15.4,0.605,0.429,...,0.0,0.0,0.1,0.164,-4.7,2.1,-2.7,0.0,NaN,CLE-2025.html
689,24.0,Darius Brown II,26.0,SG,1,0,3,-7.7,0.000,0.000,...,0.0,0.0,0.0,-0.269,-16.3,-2.4,-18.7,0.0,NaN,CLE-2025.html
690,NaN,Team Totals,NaN,NaN,82,82,19755,NaN,0.595,0.442,...,29.4,21.4,50.8,0.123,0.7,0.1,0.8,13.9,NaN,CLE-2025.html

In [ ]:
playoff_advanced_dfs = []

for team in os.listdir(playoff_teams):
    if team.endswith(".html"):
        with open(f"Data-NBA/Archive/Teams/Teams_2526/Playoff_Teams/{team}", encoding='utf-8', errors='replace') as f:
            page = f.read()
        
        soup = BeautifulSoup(page, "html.parser")

        comment = next(c for c in soup.find_all(string=lambda text: isinstance(text, Comment)) if "advanced_post" in c)
        table = BeautifulSoup(comment, "html.parser").find(id="advanced_post")
        df = pd.read_html(StringIO(str(table)))[0]
        df["team_id"] = team
        playoff_advanced_dfs.append(df)

playoff_advanced_combined = pd.concat(playoff_advanced_dfs, ignore_index=True)

playoff_advanced_combined

,Rk,Player,Age,Pos,G,GS,MP,PER,TS%,3PAr,...,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP,Awards,team_id
0,1.0,Tyrese Maxey,25.0,PG,11,11,437,18.7,0.562,0.351,...,0.7,-0.1,0.6,0.070,3.4,-0.6,2.8,0.5,NaN,PHI-2025.html
1,2.0,VJ Edgecombe,20.0,SG,11,11,407,12.3,0.504,0.497,...,0.1,0.0,0.1,0.008,-0.4,-0.2,-0.6,0.1,NaN,PHI-2025.html
2,3.0,Paul George,35.0,PF,11,11,394,14.3,0.597,0.500,...,0.3,0.0,0.3,0.038,1.5,0.7,2.2,0.4,NaN,PHI-2025.html
3,4.0,Kelly Oubre Jr.,30.0,SF,11,11,364,11.3,0.543,0.368,...,0.2,0.0,0.2,0.030,-1.5,-0.1,-1.7,0.0,NaN,PHI-2025.html
4,5.0,Quentin Grimes,25.0,SG,11,0,243,11.1,0.569,0.603,...,0.3,0.0,0.3,0.053,-0.7,0.6,-0.1,0.1,NaN,PHI-2025.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,12.0,Craig Porter Jr.,25.0,PG,7,0,21,-2.5,0.333,0.333,...,-0.1,0.0,-0.1,-0.217,-8.8,-2.4,-11.2,0.0,NaN,CLE-2025.html
242,13.0,Nae'Qwan Tomlin,25.0,PF,7,0,19,23.4,0.654,0.000,...,0.1,0.0,0.1,0.221,3.9,1.1,5.0,0.0,NaN,CLE-2025.html
243,14.0,Tyrese Proctor,21.0,PG,4,0,13,-2.5,0.347,1.000,...,-0.1,0.0,-0.1,-0.191,-9.4,-4.8,-14.3,0.0,NaN,CLE-2025.html
244,15.0,Larry Nance Jr.,33.0,PF,2,0,5,-10.3,NaN,NaN,...,0.0,0.0,0.0,-0.306,-11.1,-4.4,-15.5,0.0,NaN,CLE-2025.html
245,NaN,Team Totals,NaN,NaN,18,18,4394,NaN,0.572,0.464,...,5.0,3.1,8.1,0.088,0.8,0.4,1.2,3.6,NaN,CLE-2025.html

In [ ]:
all_adjshooting_dfs = []

for team in os.listdir(all_teams):
    if team.endswith(".html"):
        with open(f"Data-NBA/Archive/Teams/Teams_2526/All_Teams/{team}", encoding='utf-8', errors='replace') as f:
            page = f.read()
        
        soup = BeautifulSoup(page, "html.parser")

        comment = next(c for c in soup.find_all(string=lambda text: isinstance(text, Comment)) if "adj_shooting" in c)
        table = BeautifulSoup(comment, "html.parser").find(id="adj_shooting")
        df = pd.read_html(StringIO(str(table)), header=1)[0]
        df["team_id"] = team
        all_adjshooting_dfs.append(df)

all_adjshooting_combined = pd.concat(all_adjshooting_dfs, ignore_index=True)

all_adjshooting_combined

,Rk,Player,Age,Pos,G,GS,MP,FG%,2P%,3P%,...,3P+,eFG+,FT+,TS+,FTr+,3PAr+,FG Add,TS Add,Awards,team_id
0,1.0,Patrick Baldwin Jr.,23.0,SF,1,0,2,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,PHI-2025.html
1,2.0,Dominick Barlow,22.0,PF,71,59,1689,0.539,0.612,0.256,...,71.0,104.0,92.0,103.0,125.0,50.0,15.6,14.0,NaN,PHI-2025.html
2,3.0,Charles Bassey,25.0,C,1,0,5,1.000,1.000,NaN,...,NaN,183.0,NaN,172.0,0.0,0.0,0.9,0.8,NaN,PHI-2025.html
3,4.0,MarJon Beauchamp,25.0,SF,14,1,196,0.434,0.586,0.340,...,95.0,99.0,87.0,97.0,95.0,149.0,-0.9,-3.1,NaN,PHI-2025.html
4,5.0,Adem Bona,22.0,C,71,18,1234,0.595,0.603,0.333,...,93.0,110.0,90.0,110.0,195.0,7.0,23.9,30.4,NaN,PHI-2025.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
686,21.0,Nae'Qwan Tomlin,25.0,PF,64,3,1004,0.478,0.618,0.235,...,65.0,95.0,98.0,94.0,74.0,88.0,-15.7,-22.3,NaN,CLE-2025.html
687,22.0,Luke Travers,24.0,SG,12,0,103,0.250,0.400,0.063,...,17.0,48.0,128.0,60.0,95.0,107.0,-20.3,-18.5,NaN,CLE-2025.html
688,23.0,Jaylon Tyson,23.0,SG,66,42,1777,0.493,0.530,0.446,...,124.0,108.0,94.0,105.0,61.0,107.0,61.8,38.2,NaN,CLE-2025.html
689,24.0,Dean Wade,29.0,PF,59,38,1318,0.439,0.622,0.362,...,101.0,104.0,91.0,100.0,52.0,170.0,11.6,-0.7,NaN,CLE-2025.html
690,NaN,Team Totals,NaN,NaN,82,82,19755,0.482,0.578,0.360,...,100.0,103.0,99.0,102.0,101.0,106.0,226.0,215.9,NaN,CLE-2025.html

In [ ]:
playoff_adjshooting_dfs = []

for team in os.listdir(playoff_teams):
    if team.endswith(".html"):
        with open(f"Data-NBA/Archive/Teams/Teams_2526/Playoff_Teams/{team}", encoding='utf-8', errors='replace') as f:
            page = f.read()
        
        soup = BeautifulSoup(page, "html.parser")

        comment = next(c for c in soup.find_all(string=lambda text: isinstance(text, Comment)) if "adj_shooting_post" in c)
        table = BeautifulSoup(comment, "html.parser").find(id="adj_shooting_post")
        df = pd.read_html(StringIO(str(table)), header=1)[0]
        df["team_id"] = team
        playoff_adjshooting_dfs.append(df)

playoff_adjshooting_combined = pd.concat(playoff_adjshooting_dfs, ignore_index=True)

playoff_adjshooting_combined

,Rk,Player,Age,Pos,G,GS,MP,FG%,2P%,3P%,...,FG+,2P+,3P+,eFG+,FT+,TS+,FTr+,3PAr+,Awards,team_id
0,1.0,Dominick Barlow,22.0,PF,9,0,96,0.588,0.625,0.000,...,125.0,114.0,0.0,108.0,109.0,111.0,156.0,14.0,NaN,PHI-2025.html
1,2.0,Adem Bona,22.0,C,10,3,96,0.500,0.500,NaN,...,106.0,91.0,NaN,92.0,80.0,97.0,379.0,0.0,NaN,PHI-2025.html
2,3.0,Johni Broome,23.0,C,2,0,8,0.500,1.000,0.250,...,106.0,182.0,70.0,107.0,NaN,100.0,0.0,161.0,NaN,PHI-2025.html
3,4.0,Andre Drummond,32.0,C,11,1,142,0.696,0.800,0.500,...,148.0,145.0,139.0,143.0,89.0,135.0,165.0,84.0,NaN,PHI-2025.html
4,5.0,VJ Edgecombe,20.0,SG,11,11,407,0.414,0.534,0.292,...,88.0,97.0,81.0,89.0,92.0,87.0,47.0,120.0,NaN,PHI-2025.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,12.0,Max Strus,29.0,SF,18,4,481,0.406,0.563,0.358,...,86.0,102.0,100.0,100.0,117.0,100.0,66.0,185.0,NaN,CLE-2025.html
242,13.0,Nae'Qwan Tomlin,25.0,PF,7,0,19,0.667,0.667,NaN,...,142.0,121.0,NaN,122.0,64.0,112.0,126.0,0.0,NaN,CLE-2025.html
243,14.0,Jaylon Tyson,23.0,SG,17,0,216,0.362,0.516,0.237,...,77.0,94.0,66.0,78.0,85.0,78.0,82.0,133.0,NaN,CLE-2025.html
244,15.0,Dean Wade,29.0,PF,18,14,407,0.462,0.706,0.375,...,98.0,128.0,104.0,110.0,43.0,102.0,18.0,178.0,NaN,CLE-2025.html
245,NaN,Team Totals,NaN,NaN,18,18,4394,0.456,0.568,0.328,...,97.0,103.0,91.0,98.0,94.0,98.0,129.0,112.0,NaN,CLE-2025.html

In [ ]:
all_shooting_dfs = []

for team in os.listdir(all_teams):
    if team.endswith(".html"):
        with open(f"Data-NBA/Archive/Teams/Teams_2526/All_Teams/{team}", encoding='utf-8', errors='replace') as f:
            page = f.read()
        
        soup = BeautifulSoup(page, "html.parser")

        comment = next(c for c in soup.find_all(string=lambda text: isinstance(text, Comment)) if 'id="shooting"' in c)
        table = BeautifulSoup(comment, "html.parser").find(id="shooting")
        df = pd.read_html(StringIO(str(table)), header=1)[0]
        df["team_id"] = team
        all_shooting_dfs.append(df)

all_shooting_combined = pd.concat(all_shooting_dfs, ignore_index=True)

all_shooting_combined

,Rk,Player,Age,Pos,G,GS,MP,FG%,Dist.,2P,...,2P.2,3P.2,%FGA,#,%3PA,3P%,Att.,Md.,Awards,team_id
0,1.0,Tyrese Maxey,25.0,PG,70,70,2661,0.462,14.9,0.601,...,0.378,0.595,0.021,29,0.077,0.370,0,0,"CPOY-7,AS,NBA3",PHI-2025.html
1,2.0,VJ Edgecombe,20.0,SG,75,75,2623,0.438,14.8,0.591,...,0.437,0.812,0.068,58,0.138,0.345,0,0,ROY-3,PHI-2025.html
2,3.0,Quentin Grimes,25.0,SG,75,19,2206,0.450,15.7,0.497,...,0.587,0.882,0.053,35,0.226,0.419,1,1,NaN,PHI-2025.html
3,4.0,Dominick Barlow,22.0,PF,71,59,1689,0.539,7.7,0.794,...,0.665,1.000,0.180,67,0.744,0.230,0,0,NaN,PHI-2025.html
4,5.0,Kelly Oubre Jr.,30.0,SF,50,41,1574,0.467,14.1,0.561,...,0.530,0.953,0.070,34,0.335,0.463,0,0,NaN,PHI-2025.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
686,21.0,Riley Minix,25.0,SF,6,0,50,0.588,15.3,0.471,...,0.429,1.000,0.000,0,0.667,0.500,0,0,NaN,CLE-2025.html
687,22.0,Olivier Sarr,26.0,C,4,0,39,0.714,11.6,0.571,...,0.667,1.000,0.429,2,0.000,NaN,0,0,NaN,CLE-2025.html
688,23.0,Chris Livingston,22.0,SF,3,0,17,0.571,11.7,0.571,...,0.750,NaN,0.000,0,1.000,0.000,0,0,NaN,CLE-2025.html
689,24.0,Darius Brown II,26.0,SG,1,0,3,0.000,17.5,1.000,...,NaN,NaN,0.000,0,NaN,NaN,0,0,NaN,CLE-2025.html
690,NaN,Team Totals,NaN,NaN,82,82,19755,0.482,14.8,0.558,...,0.574,0.814,0.082,540,0.226,0.377,1,0,NaN,CLE-2025.html

In [ ]:
playoff_shooting_dfs = []

for team in os.listdir(playoff_teams):
    if team.endswith(".html"):
        with open(f"Data-NBA/Archive/Teams/Teams_2526/Playoff_Teams/{team}", encoding='utf-8', errors='replace') as f:
            page = f.read()
        
        soup = BeautifulSoup(page, "html.parser")

        comment = next(c for c in soup.find_all(string=lambda text: isinstance(text, Comment)) if 'id="shooting_post"' in c)
        table = BeautifulSoup(comment, "html.parser").find(id="shooting_post")
        df = pd.read_html(StringIO(str(table)), header=1)[0]
        df["team_id"] = team
        playoff_shooting_dfs.append(df)

playoff_shooting_combined = pd.concat(playoff_shooting_dfs, ignore_index=True)

playoff_shooting_combined

,Rk,Player,Age,Pos,G,GS,MP,FG%,Dist.,2P,...,2P.2,3P.2,%FGA,#,%3PA,3P%,Att.,Md.,Awards,team_id
0,1.0,Tyrese Maxey,25.0,PG,11,11,437,0.455,14.5,0.649,...,0.300,0.423,0.009,2,0.027,0.000,0,0,NaN,PHI-2025.html
1,2.0,VJ Edgecombe,20.0,SG,11,11,407,0.414,16.0,0.503,...,0.487,0.857,0.062,9,0.278,0.350,0,0,NaN,PHI-2025.html
2,3.0,Paul George,35.0,PF,11,11,394,0.458,18.8,0.500,...,0.467,0.657,0.021,3,0.169,0.583,0,0,NaN,PHI-2025.html
3,4.0,Kelly Oubre Jr.,30.0,SF,11,11,364,0.453,11.7,0.632,...,0.658,1.000,0.123,12,0.538,0.333,0,0,NaN,PHI-2025.html
4,5.0,Quentin Grimes,25.0,SG,11,0,243,0.397,17.9,0.397,...,0.778,0.929,0.069,3,0.200,0.571,0,0,NaN,PHI-2025.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,12.0,Craig Porter Jr.,25.0,PG,7,0,21,0.333,11.4,0.667,...,1.000,NaN,0.000,0,0.000,NaN,0,0,NaN,CLE-2025.html
242,13.0,Nae'Qwan Tomlin,25.0,PF,7,0,19,0.667,1.9,1.000,...,0.500,NaN,0.167,1,NaN,NaN,0,0,NaN,CLE-2025.html
243,14.0,Tyrese Proctor,21.0,PG,4,0,13,0.000,25.5,0.000,...,NaN,NaN,0.000,0,0.000,NaN,0,0,NaN,CLE-2025.html
244,15.0,Larry Nance Jr.,33.0,PF,2,0,5,NaN,NaN,NaN,...,NaN,NaN,NaN,0,NaN,NaN,0,0,NaN,CLE-2025.html
245,NaN,Team Totals,NaN,NaN,18,18,4394,0.456,15.4,0.536,...,0.492,0.751,0.065,84,0.238,0.368,0,0,NaN,CLE-2025.html

In [ ]:
all_pbp_dfs = []

for team in os.listdir(all_teams):
    if team.endswith(".html"):
        with open(f"Data-NBA/Archive/Teams/Teams_2526/All_Teams/{team}", encoding='utf-8', errors='replace') as f:
            page = f.read()
        
        soup = BeautifulSoup(page, "html.parser")

        comment = next(c for c in soup.find_all(string=lambda text: isinstance(text, Comment)) if "pbp_stats" in c)
        table = BeautifulSoup(comment, "html.parser").find(id="pbp_stats")
        df = pd.read_html(StringIO(str(table)), header=1)[0]
        df["team_id"] = team
        all_pbp_dfs.append(df)

all_pbp_combined = pd.concat(all_pbp_dfs, ignore_index=True)

all_pbp_combined

,Rk,Player,Age,Pos,G,GS,MP,PG%,SG%,SF%,...,LostBall,Shoot,Off.,Shoot.1,Off..1,PGA,And1,Blkd,Awards,team_id
0,1.0,Tyrese Maxey,25.0,PG,70,70,2661,98,3,0,...,64,69,9,175,9,1109,41,70,"CPOY-7,AS,NBA3",PHI-2025.html
1,2.0,VJ Edgecombe,20.0,SG,75,75,2623,28,72,0,...,51,126,7,82,8,754,19,54,ROY-3,PHI-2025.html
2,3.0,Quentin Grimes,25.0,SG,75,19,2206,1,55,43,...,47,83,6,100,18,590,20,31,NaN,PHI-2025.html
3,4.0,Dominick Barlow,22.0,PF,71,59,1689,0,0,0,...,15,86,9,74,2,219,23,26,NaN,PHI-2025.html
4,5.0,Kelly Oubre Jr.,30.0,SF,50,41,1574,0,2,75,...,26,63,5,74,20,184,20,33,NaN,PHI-2025.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
686,21.0,Riley Minix,25.0,SF,6,0,50,0,20,51,...,0,1,1,2,0,10,1,0,NaN,CLE-2025.html
687,22.0,Olivier Sarr,26.0,C,4,0,39,0,0,0,...,1,5,1,1,0,11,0,0,NaN,CLE-2025.html
688,23.0,Chris Livingston,22.0,SF,3,0,17,0,0,100,...,0,1,0,1,0,2,1,0,NaN,CLE-2025.html
689,24.0,Darius Brown II,26.0,SG,1,0,3,0,0,100,...,0,0,0,0,0,0,0,0,NaN,CLE-2025.html
690,NaN,Team Totals,NaN,NaN,82,82,19755,20,20,20,...,332,802,86,838,114,5597,191,354,NaN,CLE-2025.html

In [ ]:
playoff_pbp_dfs = []

for team in os.listdir(playoff_teams):
    if team.endswith(".html"):
        with open(f"Data-NBA/Archive/Teams/Teams_2526/Playoff_Teams/{team}", encoding='utf-8', errors='replace') as f:
            page = f.read()
        
        soup = BeautifulSoup(page, "html.parser")

        comment = next(c for c in soup.find_all(string=lambda text: isinstance(text, Comment)) if "pbp_stats_post" in c)
        table = BeautifulSoup(comment, "html.parser").find(id="pbp_stats_post")
        df = pd.read_html(StringIO(str(table)), header=1)[0]
        df["team_id"] = team
        playoff_pbp_dfs.append(df)

playoff_pbp_combined = pd.concat(playoff_pbp_dfs, ignore_index=True)

playoff_pbp_combined

,Rk,Player,Age,Pos,G,GS,MP,PG%,SG%,SF%,...,LostBall,Shoot,Off.,Shoot.1,Off..1,PGA,And1,Blkd,Awards,team_id
0,1.0,Tyrese Maxey,25.0,PG,11,11,437,100,0,0,...,6,10,2,20,2,155,5,11,NaN,PHI-2025.html
1,2.0,VJ Edgecombe,20.0,SG,11,11,407,13,88,0,...,4,17,2,9,5,93,2,6,NaN,PHI-2025.html
2,3.0,Paul George,35.0,PF,11,11,394,0,0,2,...,7,8,4,10,6,76,4,6,NaN,PHI-2025.html
3,4.0,Kelly Oubre Jr.,30.0,SF,11,11,364,0,0,84,...,5,13,1,14,14,30,4,8,NaN,PHI-2025.html
4,5.0,Quentin Grimes,25.0,SG,11,0,243,5,51,44,...,2,5,0,7,1,59,1,3,NaN,PHI-2025.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,12.0,Craig Porter Jr.,25.0,PG,7,0,21,100,0,0,...,1,0,0,0,0,9,0,0,NaN,CLE-2025.html
242,13.0,Nae'Qwan Tomlin,25.0,PF,7,0,19,0,0,0,...,0,2,1,1,0,5,0,0,NaN,CLE-2025.html
243,14.0,Tyrese Proctor,21.0,PG,4,0,13,0,100,0,...,1,0,0,1,0,5,0,0,NaN,CLE-2025.html
244,15.0,Larry Nance Jr.,33.0,PF,2,0,5,0,0,57,...,0,0,0,0,0,0,0,0,NaN,CLE-2025.html
245,NaN,Team Totals,NaN,NaN,18,18,4394,20,20,20,...,96,175,27,200,34,949,34,89,NaN,CLE-2025.html

In [ ]:
all_team_dfs_dict = {
    "pgs": all_pgs_combined,
    "misc": all_misc_combined,
    "totals": all_totals_combined,
    "per36": all_per36_combined,
    "per100": all_per100_combined,
    "advanced": all_advanced_combined,
    "adjshooting": all_adjshooting_combined,
    "shooting": all_shooting_combined,
    "pbp": all_pbp_combined
}

for name, df in all_team_dfs_dict.items():
    df.to_csv(f"Data-NBA/Adding-2526/{name}-2526.csv", index=False)

In [ ]:
playoff_team_dfs_dict = {
    "playoff_pgs": playoff_pgs_combined,
    "playoff_totals": playoff_totals_combined,
    "playoff_per36": playoff_per36_combined,
    "playoff_per100": playoff_per100_combined,
    "playoff_advanced": playoff_advanced_combined,
    "playoff_adjshooting": playoff_adjshooting_combined,
    "playoff_shooting": playoff_shooting_combined,
    "playoff_pbp": playoff_pbp_combined
}

for name, df in playoff_team_dfs_dict.items():
    df.to_csv(f"Data-NBA/Adding-2526/{name}-2526.csv", index=False)